export const options = {
  sizes: ['xs', 'sm', 'md', 'lg', 'xl'],
  types: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'span', 'p'],
  weights: ['light', 'regular', 'medium', 'bold'],
  alignments: ['left', 'center', 'right'],
  transforms: ['capitalize', 'uppercase', 'lowercase', 'initial'],
  colors: [
    '50',
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
    '950',
  ],
}
