export const options = {
  sizes: ['xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl'],
  types: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'span', 'p'],
  weights: ['light', 'regular', 'medium', 'bold'],
  alignments: ['left', 'center', 'right'],
  transforms: ['capitalize', 'uppercase', 'lowercase', 'initial'],
  colors: [
    'primary',
    'primary-dark',
    'primary-darker',
    'neutral-lighter',
    'neutral-light',
    'neutral-dark',
    'neutral-darker',
    'disabled',
    'error',
    'error-dark',
    'success',
    'success-dark',
    'success-darker',
    'warning',
    'warning-dark',
  ],
}
